// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(getstorageitem,"vi?"),
BUILDIN_DEF(getstorageitem2,"viiiiiiii?"),
BUILDIN_DEF2(getstorageitem2,"getstorageitem3","viiiiiiiirrr?"),